### ISSUE TITLE
Continuously outputs file in watch mode with no changes

### ISSUE THREAD

**Issue by mtscout6** [mtscout6/asset-map-webpack-plugin#1]
If you run webpack in watch mode the resulting assets json file is continuously written/re-written to disk, even when there are no changes. @sokra Do you have any suggestions on how I can improve that?

**Comment by sokra** [comment]
You need to emit the same asset instance for the same result. The Compiler sets a `emitted` property on each emitted asset.

**Comment by mtscout6** [comment]
@sokra Thanks for the pointer, does that commit look like enough to fix this?

**Comment by mtscout6** [comment]
Ah, never mind that commit didn't quite do it.

**Comment by mtscout6** [comment]
There, that one should be better.
