### ISSUE TITLE
This plugin doesn't seem to do anything; did something change in webpack making this not compatible?

### ISSUE THREAD

**Issue by simensen** [mtscout6/asset-map-webpack-plugin#5]
I've done a little bit of debugging and it appears that `.assets` is empty for all of my modules. The end result is that extracted assets ends up with a bunch of empty `{}` for which nothing goes into the asset dump.

It is possible I'm doing something wrong/configuring it wrong, but it seems like there isn't a lot of configuration that might be leading to this different behavior. It seems like maybe either webpack itself is configured differently, things are happening in the wrong order, or the internal structure has changed such that the `.assets` property no longer contains the information this plugin is looking for.

**Comment by mtscout6** [comment]
Have you tried it with an older version of Webpack to confirm the issue? Which version are you using?

**Comment by schneidmaster** [comment]
Closing out this issue for now, feel free to follow up if you do have a bug report.
